//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PMS.PMS_Entries {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PMS_EntriesSoap", Namespace="http://tempuri.org/")]
    public partial class PMS_Entries : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PigDetailRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PigDetailSaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatingDetailRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatingDetailSaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatingSaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatingRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback FarrowingDetailRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback FarrowingDetailSaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback WeaningDetailRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback WeaningPigletsDetailRetrieveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PMS_Entries() {
            this.Url = global::PMS.Properties.Settings.Default.PMS_PMS_Entries_PMS_Entries;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PigDetailRetrieveCompletedEventHandler PigDetailRetrieveCompleted;
        
        /// <remarks/>
        public event PigDetailSaveCompletedEventHandler PigDetailSaveCompleted;
        
        /// <remarks/>
        public event MatingDetailRetrieveCompletedEventHandler MatingDetailRetrieveCompleted;
        
        /// <remarks/>
        public event MatingDetailSaveCompletedEventHandler MatingDetailSaveCompleted;
        
        /// <remarks/>
        public event MatingSaveCompletedEventHandler MatingSaveCompleted;
        
        /// <remarks/>
        public event MatingRetrieveCompletedEventHandler MatingRetrieveCompleted;
        
        /// <remarks/>
        public event FarrowingDetailRetrieveCompletedEventHandler FarrowingDetailRetrieveCompleted;
        
        /// <remarks/>
        public event FarrowingDetailSaveCompletedEventHandler FarrowingDetailSaveCompleted;
        
        /// <remarks/>
        public event WeaningDetailRetrieveCompletedEventHandler WeaningDetailRetrieveCompleted;
        
        /// <remarks/>
        public event WeaningPigletsDetailRetrieveCompletedEventHandler WeaningPigletsDetailRetrieveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PigDetailRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PigDetail PigDetailRetrieve(string strTagno) {
            object[] results = this.Invoke("PigDetailRetrieve", new object[] {
                        strTagno});
            return ((PigDetail)(results[0]));
        }
        
        /// <remarks/>
        public void PigDetailRetrieveAsync(string strTagno) {
            this.PigDetailRetrieveAsync(strTagno, null);
        }
        
        /// <remarks/>
        public void PigDetailRetrieveAsync(string strTagno, object userState) {
            if ((this.PigDetailRetrieveOperationCompleted == null)) {
                this.PigDetailRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPigDetailRetrieveOperationCompleted);
            }
            this.InvokeAsync("PigDetailRetrieve", new object[] {
                        strTagno}, this.PigDetailRetrieveOperationCompleted, userState);
        }
        
        private void OnPigDetailRetrieveOperationCompleted(object arg) {
            if ((this.PigDetailRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PigDetailRetrieveCompleted(this, new PigDetailRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PigDetailSave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PigDetailSave(PigDetail pd) {
            object[] results = this.Invoke("PigDetailSave", new object[] {
                        pd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PigDetailSaveAsync(PigDetail pd) {
            this.PigDetailSaveAsync(pd, null);
        }
        
        /// <remarks/>
        public void PigDetailSaveAsync(PigDetail pd, object userState) {
            if ((this.PigDetailSaveOperationCompleted == null)) {
                this.PigDetailSaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPigDetailSaveOperationCompleted);
            }
            this.InvokeAsync("PigDetailSave", new object[] {
                        pd}, this.PigDetailSaveOperationCompleted, userState);
        }
        
        private void OnPigDetailSaveOperationCompleted(object arg) {
            if ((this.PigDetailSaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PigDetailSaveCompleted(this, new PigDetailSaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MatingDetailRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MatingDetail[] MatingDetailRetrieve(string strTagno) {
            object[] results = this.Invoke("MatingDetailRetrieve", new object[] {
                        strTagno});
            return ((MatingDetail[])(results[0]));
        }
        
        /// <remarks/>
        public void MatingDetailRetrieveAsync(string strTagno) {
            this.MatingDetailRetrieveAsync(strTagno, null);
        }
        
        /// <remarks/>
        public void MatingDetailRetrieveAsync(string strTagno, object userState) {
            if ((this.MatingDetailRetrieveOperationCompleted == null)) {
                this.MatingDetailRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatingDetailRetrieveOperationCompleted);
            }
            this.InvokeAsync("MatingDetailRetrieve", new object[] {
                        strTagno}, this.MatingDetailRetrieveOperationCompleted, userState);
        }
        
        private void OnMatingDetailRetrieveOperationCompleted(object arg) {
            if ((this.MatingDetailRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatingDetailRetrieveCompleted(this, new MatingDetailRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MatingDetailSave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MatingDetailSave(MatingDetail md) {
            object[] results = this.Invoke("MatingDetailSave", new object[] {
                        md});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MatingDetailSaveAsync(MatingDetail md) {
            this.MatingDetailSaveAsync(md, null);
        }
        
        /// <remarks/>
        public void MatingDetailSaveAsync(MatingDetail md, object userState) {
            if ((this.MatingDetailSaveOperationCompleted == null)) {
                this.MatingDetailSaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatingDetailSaveOperationCompleted);
            }
            this.InvokeAsync("MatingDetailSave", new object[] {
                        md}, this.MatingDetailSaveOperationCompleted, userState);
        }
        
        private void OnMatingDetailSaveOperationCompleted(object arg) {
            if ((this.MatingDetailSaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatingDetailSaveCompleted(this, new MatingDetailSaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MatingSave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MatingSave(MatingDetail md) {
            object[] results = this.Invoke("MatingSave", new object[] {
                        md});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MatingSaveAsync(MatingDetail md) {
            this.MatingSaveAsync(md, null);
        }
        
        /// <remarks/>
        public void MatingSaveAsync(MatingDetail md, object userState) {
            if ((this.MatingSaveOperationCompleted == null)) {
                this.MatingSaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatingSaveOperationCompleted);
            }
            this.InvokeAsync("MatingSave", new object[] {
                        md}, this.MatingSaveOperationCompleted, userState);
        }
        
        private void OnMatingSaveOperationCompleted(object arg) {
            if ((this.MatingSaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatingSaveCompleted(this, new MatingSaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MatingRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FarrowingDetail MatingRetrieve(string strTagno) {
            object[] results = this.Invoke("MatingRetrieve", new object[] {
                        strTagno});
            return ((FarrowingDetail)(results[0]));
        }
        
        /// <remarks/>
        public void MatingRetrieveAsync(string strTagno) {
            this.MatingRetrieveAsync(strTagno, null);
        }
        
        /// <remarks/>
        public void MatingRetrieveAsync(string strTagno, object userState) {
            if ((this.MatingRetrieveOperationCompleted == null)) {
                this.MatingRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatingRetrieveOperationCompleted);
            }
            this.InvokeAsync("MatingRetrieve", new object[] {
                        strTagno}, this.MatingRetrieveOperationCompleted, userState);
        }
        
        private void OnMatingRetrieveOperationCompleted(object arg) {
            if ((this.MatingRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatingRetrieveCompleted(this, new MatingRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FarrowingDetailRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FarrowingDetail[] FarrowingDetailRetrieve(string strTagno) {
            object[] results = this.Invoke("FarrowingDetailRetrieve", new object[] {
                        strTagno});
            return ((FarrowingDetail[])(results[0]));
        }
        
        /// <remarks/>
        public void FarrowingDetailRetrieveAsync(string strTagno) {
            this.FarrowingDetailRetrieveAsync(strTagno, null);
        }
        
        /// <remarks/>
        public void FarrowingDetailRetrieveAsync(string strTagno, object userState) {
            if ((this.FarrowingDetailRetrieveOperationCompleted == null)) {
                this.FarrowingDetailRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFarrowingDetailRetrieveOperationCompleted);
            }
            this.InvokeAsync("FarrowingDetailRetrieve", new object[] {
                        strTagno}, this.FarrowingDetailRetrieveOperationCompleted, userState);
        }
        
        private void OnFarrowingDetailRetrieveOperationCompleted(object arg) {
            if ((this.FarrowingDetailRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FarrowingDetailRetrieveCompleted(this, new FarrowingDetailRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FarrowingDetailSave", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FarrowingDetailSave(FarrowingDetail fd) {
            object[] results = this.Invoke("FarrowingDetailSave", new object[] {
                        fd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FarrowingDetailSaveAsync(FarrowingDetail fd) {
            this.FarrowingDetailSaveAsync(fd, null);
        }
        
        /// <remarks/>
        public void FarrowingDetailSaveAsync(FarrowingDetail fd, object userState) {
            if ((this.FarrowingDetailSaveOperationCompleted == null)) {
                this.FarrowingDetailSaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFarrowingDetailSaveOperationCompleted);
            }
            this.InvokeAsync("FarrowingDetailSave", new object[] {
                        fd}, this.FarrowingDetailSaveOperationCompleted, userState);
        }
        
        private void OnFarrowingDetailSaveOperationCompleted(object arg) {
            if ((this.FarrowingDetailSaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FarrowingDetailSaveCompleted(this, new FarrowingDetailSaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WeaningDetailRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WeaningDetail[] WeaningDetailRetrieve(string strTagNo) {
            object[] results = this.Invoke("WeaningDetailRetrieve", new object[] {
                        strTagNo});
            return ((WeaningDetail[])(results[0]));
        }
        
        /// <remarks/>
        public void WeaningDetailRetrieveAsync(string strTagNo) {
            this.WeaningDetailRetrieveAsync(strTagNo, null);
        }
        
        /// <remarks/>
        public void WeaningDetailRetrieveAsync(string strTagNo, object userState) {
            if ((this.WeaningDetailRetrieveOperationCompleted == null)) {
                this.WeaningDetailRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWeaningDetailRetrieveOperationCompleted);
            }
            this.InvokeAsync("WeaningDetailRetrieve", new object[] {
                        strTagNo}, this.WeaningDetailRetrieveOperationCompleted, userState);
        }
        
        private void OnWeaningDetailRetrieveOperationCompleted(object arg) {
            if ((this.WeaningDetailRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WeaningDetailRetrieveCompleted(this, new WeaningDetailRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WeaningPigletsDetailRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WeaningDetail[] WeaningPigletsDetailRetrieve(string strTagNo) {
            object[] results = this.Invoke("WeaningPigletsDetailRetrieve", new object[] {
                        strTagNo});
            return ((WeaningDetail[])(results[0]));
        }
        
        /// <remarks/>
        public void WeaningPigletsDetailRetrieveAsync(string strTagNo) {
            this.WeaningPigletsDetailRetrieveAsync(strTagNo, null);
        }
        
        /// <remarks/>
        public void WeaningPigletsDetailRetrieveAsync(string strTagNo, object userState) {
            if ((this.WeaningPigletsDetailRetrieveOperationCompleted == null)) {
                this.WeaningPigletsDetailRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWeaningPigletsDetailRetrieveOperationCompleted);
            }
            this.InvokeAsync("WeaningPigletsDetailRetrieve", new object[] {
                        strTagNo}, this.WeaningPigletsDetailRetrieveOperationCompleted, userState);
        }
        
        private void OnWeaningPigletsDetailRetrieveOperationCompleted(object arg) {
            if ((this.WeaningPigletsDetailRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WeaningPigletsDetailRetrieveCompleted(this, new WeaningPigletsDetailRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PigDetail {
        
        private string tagnoField;
        
        private int statusIdField;
        
        private string statusField;
        
        private int schemeIdField;
        
        private string schemeNameField;
        
        private int breedIdField;
        
        private string breedNameField;
        
        private string dOBField;
        
        private int sexField;
        
        private System.Nullable<double> birthWeightField;
        
        private string colorField;
        
        private string sirenoField;
        
        private string damnoField;
        
        private System.Nullable<int> shedIdField;
        
        private string shedNameField;
        
        private System.Nullable<int> penIdField;
        
        private string pennoField;
        
        private System.Nullable<int> generationField;
        
        private string periodSeasonField;
        
        private System.Nullable<int> noofTeatsField;
        
        private System.Nullable<int> teatsTypeField;
        
        private System.Nullable<int> castRatedField;
        
        private string castRatedDateField;
        
        private int userIdField;
        
        private string stageField;
        
        private string sexualMaturityDateField;
        
        private System.Nullable<double> sexualMaturityWeightField;
        
        private System.Nullable<int> sexualMaturityAgeField;
        
        private string firstServiceDateField;
        
        private System.Nullable<double> firstServiceWeightField;
        
        private System.Nullable<int> firstServiceAgeField;
        
        /// <remarks/>
        public string Tagno {
            get {
                return this.tagnoField;
            }
            set {
                this.tagnoField = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int SchemeId {
            get {
                return this.schemeIdField;
            }
            set {
                this.schemeIdField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeName {
            get {
                return this.schemeNameField;
            }
            set {
                this.schemeNameField = value;
            }
        }
        
        /// <remarks/>
        public int BreedId {
            get {
                return this.breedIdField;
            }
            set {
                this.breedIdField = value;
            }
        }
        
        /// <remarks/>
        public string BreedName {
            get {
                return this.breedNameField;
            }
            set {
                this.breedNameField = value;
            }
        }
        
        /// <remarks/>
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public int Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BirthWeight {
            get {
                return this.birthWeightField;
            }
            set {
                this.birthWeightField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Sireno {
            get {
                return this.sirenoField;
            }
            set {
                this.sirenoField = value;
            }
        }
        
        /// <remarks/>
        public string Damno {
            get {
                return this.damnoField;
            }
            set {
                this.damnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ShedId {
            get {
                return this.shedIdField;
            }
            set {
                this.shedIdField = value;
            }
        }
        
        /// <remarks/>
        public string ShedName {
            get {
                return this.shedNameField;
            }
            set {
                this.shedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PenId {
            get {
                return this.penIdField;
            }
            set {
                this.penIdField = value;
            }
        }
        
        /// <remarks/>
        public string Penno {
            get {
                return this.pennoField;
            }
            set {
                this.pennoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Generation {
            get {
                return this.generationField;
            }
            set {
                this.generationField = value;
            }
        }
        
        /// <remarks/>
        public string PeriodSeason {
            get {
                return this.periodSeasonField;
            }
            set {
                this.periodSeasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NoofTeats {
            get {
                return this.noofTeatsField;
            }
            set {
                this.noofTeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TeatsType {
            get {
                return this.teatsTypeField;
            }
            set {
                this.teatsTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CastRated {
            get {
                return this.castRatedField;
            }
            set {
                this.castRatedField = value;
            }
        }
        
        /// <remarks/>
        public string CastRatedDate {
            get {
                return this.castRatedDateField;
            }
            set {
                this.castRatedDateField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
            }
        }
        
        /// <remarks/>
        public string SexualMaturityDate {
            get {
                return this.sexualMaturityDateField;
            }
            set {
                this.sexualMaturityDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> SexualMaturityWeight {
            get {
                return this.sexualMaturityWeightField;
            }
            set {
                this.sexualMaturityWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SexualMaturityAge {
            get {
                return this.sexualMaturityAgeField;
            }
            set {
                this.sexualMaturityAgeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstServiceDate {
            get {
                return this.firstServiceDateField;
            }
            set {
                this.firstServiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> FirstServiceWeight {
            get {
                return this.firstServiceWeightField;
            }
            set {
                this.firstServiceWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FirstServiceAge {
            get {
                return this.firstServiceAgeField;
            }
            set {
                this.firstServiceAgeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WeaningDetail {
        
        private int weaningIdField;
        
        private string tagNoField;
        
        private string matingDateField;
        
        private string farrowingDateField;
        
        private string weaningDateField;
        
        private string boarNoField;
        
        private int sexField;
        
        private System.Nullable<double> birthWeightField;
        
        private System.Nullable<double> weaningWeightField;
        
        private int statusIdField;
        
        private string shedNameField;
        
        private string penNoField;
        
        private int penIdField;
        
        private int shedIdField;
        
        /// <remarks/>
        public int WeaningId {
            get {
                return this.weaningIdField;
            }
            set {
                this.weaningIdField = value;
            }
        }
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public string MatingDate {
            get {
                return this.matingDateField;
            }
            set {
                this.matingDateField = value;
            }
        }
        
        /// <remarks/>
        public string FarrowingDate {
            get {
                return this.farrowingDateField;
            }
            set {
                this.farrowingDateField = value;
            }
        }
        
        /// <remarks/>
        public string WeaningDate {
            get {
                return this.weaningDateField;
            }
            set {
                this.weaningDateField = value;
            }
        }
        
        /// <remarks/>
        public string BoarNo {
            get {
                return this.boarNoField;
            }
            set {
                this.boarNoField = value;
            }
        }
        
        /// <remarks/>
        public int Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BirthWeight {
            get {
                return this.birthWeightField;
            }
            set {
                this.birthWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> WeaningWeight {
            get {
                return this.weaningWeightField;
            }
            set {
                this.weaningWeightField = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        public string ShedName {
            get {
                return this.shedNameField;
            }
            set {
                this.shedNameField = value;
            }
        }
        
        /// <remarks/>
        public string PenNo {
            get {
                return this.penNoField;
            }
            set {
                this.penNoField = value;
            }
        }
        
        /// <remarks/>
        public int PenId {
            get {
                return this.penIdField;
            }
            set {
                this.penIdField = value;
            }
        }
        
        /// <remarks/>
        public int ShedId {
            get {
                return this.shedIdField;
            }
            set {
                this.shedIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FarrowingDetail {
        
        private long farrowingIdField;
        
        private string sownoField;
        
        private long matingIdField;
        
        private string matingDateField;
        
        private string boarnoField;
        
        private string farrowingDateField;
        
        private System.Nullable<int> sBMField;
        
        private System.Nullable<int> sBFField;
        
        private System.Nullable<int> sBTField;
        
        private System.Nullable<int> lSBMField;
        
        private System.Nullable<int> lSBFField;
        
        private System.Nullable<int> lSBTField;
        
        private System.Nullable<int> lWBMField;
        
        private System.Nullable<int> lWBFField;
        
        private System.Nullable<int> lWBTField;
        
        private int breedIdField;
        
        private string breedField;
        
        private System.Nullable<int> generationField;
        
        private FarrowingDetail[] pigletsField;
        
        private string pigletsDataField;
        
        private string tagnoField;
        
        private int sexField;
        
        private double birthWeightField;
        
        private string colorField;
        
        private System.Nullable<int> noofTeatsField;
        
        private System.Nullable<int> teatsTypeField;
        
        private int reultField;
        
        private int userIdField;
        
        /// <remarks/>
        public long FarrowingId {
            get {
                return this.farrowingIdField;
            }
            set {
                this.farrowingIdField = value;
            }
        }
        
        /// <remarks/>
        public string Sowno {
            get {
                return this.sownoField;
            }
            set {
                this.sownoField = value;
            }
        }
        
        /// <remarks/>
        public long MatingId {
            get {
                return this.matingIdField;
            }
            set {
                this.matingIdField = value;
            }
        }
        
        /// <remarks/>
        public string MatingDate {
            get {
                return this.matingDateField;
            }
            set {
                this.matingDateField = value;
            }
        }
        
        /// <remarks/>
        public string Boarno {
            get {
                return this.boarnoField;
            }
            set {
                this.boarnoField = value;
            }
        }
        
        /// <remarks/>
        public string FarrowingDate {
            get {
                return this.farrowingDateField;
            }
            set {
                this.farrowingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SBM {
            get {
                return this.sBMField;
            }
            set {
                this.sBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SBF {
            get {
                return this.sBFField;
            }
            set {
                this.sBFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SBT {
            get {
                return this.sBTField;
            }
            set {
                this.sBTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LSBM {
            get {
                return this.lSBMField;
            }
            set {
                this.lSBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LSBF {
            get {
                return this.lSBFField;
            }
            set {
                this.lSBFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LSBT {
            get {
                return this.lSBTField;
            }
            set {
                this.lSBTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LWBM {
            get {
                return this.lWBMField;
            }
            set {
                this.lWBMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LWBF {
            get {
                return this.lWBFField;
            }
            set {
                this.lWBFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LWBT {
            get {
                return this.lWBTField;
            }
            set {
                this.lWBTField = value;
            }
        }
        
        /// <remarks/>
        public int BreedId {
            get {
                return this.breedIdField;
            }
            set {
                this.breedIdField = value;
            }
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Generation {
            get {
                return this.generationField;
            }
            set {
                this.generationField = value;
            }
        }
        
        /// <remarks/>
        public FarrowingDetail[] Piglets {
            get {
                return this.pigletsField;
            }
            set {
                this.pigletsField = value;
            }
        }
        
        /// <remarks/>
        public string PigletsData {
            get {
                return this.pigletsDataField;
            }
            set {
                this.pigletsDataField = value;
            }
        }
        
        /// <remarks/>
        public string Tagno {
            get {
                return this.tagnoField;
            }
            set {
                this.tagnoField = value;
            }
        }
        
        /// <remarks/>
        public int Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public double BirthWeight {
            get {
                return this.birthWeightField;
            }
            set {
                this.birthWeightField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NoofTeats {
            get {
                return this.noofTeatsField;
            }
            set {
                this.noofTeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TeatsType {
            get {
                return this.teatsTypeField;
            }
            set {
                this.teatsTypeField = value;
            }
        }
        
        /// <remarks/>
        public int Reult {
            get {
                return this.reultField;
            }
            set {
                this.reultField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MatingDetail {
        
        private string tagnoField;
        
        private string sexualMaturityDateField;
        
        private double sexualMaturityWeightField;
        
        private int sexualMaturityAgeField;
        
        private string firstServiceDateField;
        
        private double firstServiceWeightField;
        
        private int firstServiceAgeField;
        
        private long matingIdField;
        
        private string matingDateField;
        
        private string sirenoField;
        
        private string damnoField;
        
        private string boarnoField;
        
        private int matingStatusIdField;
        
        private string matingStatusField;
        
        private int userIdField;
        
        /// <remarks/>
        public string Tagno {
            get {
                return this.tagnoField;
            }
            set {
                this.tagnoField = value;
            }
        }
        
        /// <remarks/>
        public string SexualMaturityDate {
            get {
                return this.sexualMaturityDateField;
            }
            set {
                this.sexualMaturityDateField = value;
            }
        }
        
        /// <remarks/>
        public double SexualMaturityWeight {
            get {
                return this.sexualMaturityWeightField;
            }
            set {
                this.sexualMaturityWeightField = value;
            }
        }
        
        /// <remarks/>
        public int SexualMaturityAge {
            get {
                return this.sexualMaturityAgeField;
            }
            set {
                this.sexualMaturityAgeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstServiceDate {
            get {
                return this.firstServiceDateField;
            }
            set {
                this.firstServiceDateField = value;
            }
        }
        
        /// <remarks/>
        public double FirstServiceWeight {
            get {
                return this.firstServiceWeightField;
            }
            set {
                this.firstServiceWeightField = value;
            }
        }
        
        /// <remarks/>
        public int FirstServiceAge {
            get {
                return this.firstServiceAgeField;
            }
            set {
                this.firstServiceAgeField = value;
            }
        }
        
        /// <remarks/>
        public long MatingId {
            get {
                return this.matingIdField;
            }
            set {
                this.matingIdField = value;
            }
        }
        
        /// <remarks/>
        public string MatingDate {
            get {
                return this.matingDateField;
            }
            set {
                this.matingDateField = value;
            }
        }
        
        /// <remarks/>
        public string Sireno {
            get {
                return this.sirenoField;
            }
            set {
                this.sirenoField = value;
            }
        }
        
        /// <remarks/>
        public string Damno {
            get {
                return this.damnoField;
            }
            set {
                this.damnoField = value;
            }
        }
        
        /// <remarks/>
        public string Boarno {
            get {
                return this.boarnoField;
            }
            set {
                this.boarnoField = value;
            }
        }
        
        /// <remarks/>
        public int MatingStatusId {
            get {
                return this.matingStatusIdField;
            }
            set {
                this.matingStatusIdField = value;
            }
        }
        
        /// <remarks/>
        public string MatingStatus {
            get {
                return this.matingStatusField;
            }
            set {
                this.matingStatusField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PigDetailRetrieveCompletedEventHandler(object sender, PigDetailRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PigDetailRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PigDetailRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PigDetail Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PigDetail)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PigDetailSaveCompletedEventHandler(object sender, PigDetailSaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PigDetailSaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PigDetailSaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MatingDetailRetrieveCompletedEventHandler(object sender, MatingDetailRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatingDetailRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatingDetailRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MatingDetail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MatingDetail[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MatingDetailSaveCompletedEventHandler(object sender, MatingDetailSaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatingDetailSaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatingDetailSaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MatingSaveCompletedEventHandler(object sender, MatingSaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatingSaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatingSaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MatingRetrieveCompletedEventHandler(object sender, MatingRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatingRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatingRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FarrowingDetail Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FarrowingDetail)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FarrowingDetailRetrieveCompletedEventHandler(object sender, FarrowingDetailRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FarrowingDetailRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FarrowingDetailRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FarrowingDetail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FarrowingDetail[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FarrowingDetailSaveCompletedEventHandler(object sender, FarrowingDetailSaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FarrowingDetailSaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FarrowingDetailSaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WeaningDetailRetrieveCompletedEventHandler(object sender, WeaningDetailRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeaningDetailRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WeaningDetailRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WeaningDetail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WeaningDetail[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WeaningPigletsDetailRetrieveCompletedEventHandler(object sender, WeaningPigletsDetailRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeaningPigletsDetailRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WeaningPigletsDetailRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WeaningDetail[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WeaningDetail[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591