//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PMS.PMS_Common {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PMS_CommonSoap", Namespace="http://tempuri.org/")]
    public partial class PMS_Common : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback TagnoAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SchemeAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BreedAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShedAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PenAutoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatusRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MatingStatusRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback TagnoCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback PigDetailUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback WeightRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback StageRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PigListRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupBasedStatusRetrieveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PMS_Common() {
            this.Url = global::PMS.Properties.Settings.Default.PMS_PMS_Common_PMS_Common;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event TagnoAutoCompletedEventHandler TagnoAutoCompleted;
        
        /// <remarks/>
        public event SchemeAutoCompletedEventHandler SchemeAutoCompleted;
        
        /// <remarks/>
        public event BreedAutoCompletedEventHandler BreedAutoCompleted;
        
        /// <remarks/>
        public event ShedAutoCompletedEventHandler ShedAutoCompleted;
        
        /// <remarks/>
        public event PenAutoCompletedEventHandler PenAutoCompleted;
        
        /// <remarks/>
        public event StatusRetrieveCompletedEventHandler StatusRetrieveCompleted;
        
        /// <remarks/>
        public event MatingStatusRetrieveCompletedEventHandler MatingStatusRetrieveCompleted;
        
        /// <remarks/>
        public event TagnoCheckCompletedEventHandler TagnoCheckCompleted;
        
        /// <remarks/>
        public event PigDetailUpdateCompletedEventHandler PigDetailUpdateCompleted;
        
        /// <remarks/>
        public event WeightRetrieveCompletedEventHandler WeightRetrieveCompleted;
        
        /// <remarks/>
        public event StageRetrieveCompletedEventHandler StageRetrieveCompleted;
        
        /// <remarks/>
        public event PigListRetrieveCompletedEventHandler PigListRetrieveCompleted;
        
        /// <remarks/>
        public event GroupBasedStatusRetrieveCompletedEventHandler GroupBasedStatusRetrieveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendEmail(string strUserId, string strUserName, string strToEmailId) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        strUserId,
                        strUserName,
                        strToEmailId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(string strUserId, string strUserName, string strToEmailId) {
            this.SendEmailAsync(strUserId, strUserName, strToEmailId, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string strUserId, string strUserName, string strToEmailId, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        strUserId,
                        strUserName,
                        strToEmailId}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TagnoAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] TagnoAuto(string strStatusId, int intSex, int intId, string strCondition, string strValue, int intUserId) {
            object[] results = this.Invoke("TagnoAuto", new object[] {
                        strStatusId,
                        intSex,
                        intId,
                        strCondition,
                        strValue,
                        intUserId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void TagnoAutoAsync(string strStatusId, int intSex, int intId, string strCondition, string strValue, int intUserId) {
            this.TagnoAutoAsync(strStatusId, intSex, intId, strCondition, strValue, intUserId, null);
        }
        
        /// <remarks/>
        public void TagnoAutoAsync(string strStatusId, int intSex, int intId, string strCondition, string strValue, int intUserId, object userState) {
            if ((this.TagnoAutoOperationCompleted == null)) {
                this.TagnoAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTagnoAutoOperationCompleted);
            }
            this.InvokeAsync("TagnoAuto", new object[] {
                        strStatusId,
                        intSex,
                        intId,
                        strCondition,
                        strValue,
                        intUserId}, this.TagnoAutoOperationCompleted, userState);
        }
        
        private void OnTagnoAutoOperationCompleted(object arg) {
            if ((this.TagnoAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TagnoAutoCompleted(this, new TagnoAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SchemeAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SchemeAuto(int intUserId, string strValue) {
            object[] results = this.Invoke("SchemeAuto", new object[] {
                        intUserId,
                        strValue});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SchemeAutoAsync(int intUserId, string strValue) {
            this.SchemeAutoAsync(intUserId, strValue, null);
        }
        
        /// <remarks/>
        public void SchemeAutoAsync(int intUserId, string strValue, object userState) {
            if ((this.SchemeAutoOperationCompleted == null)) {
                this.SchemeAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSchemeAutoOperationCompleted);
            }
            this.InvokeAsync("SchemeAuto", new object[] {
                        intUserId,
                        strValue}, this.SchemeAutoOperationCompleted, userState);
        }
        
        private void OnSchemeAutoOperationCompleted(object arg) {
            if ((this.SchemeAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SchemeAutoCompleted(this, new SchemeAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BreedAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] BreedAuto(int intUserId, int intSchemeId, string strValue) {
            object[] results = this.Invoke("BreedAuto", new object[] {
                        intUserId,
                        intSchemeId,
                        strValue});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void BreedAutoAsync(int intUserId, int intSchemeId, string strValue) {
            this.BreedAutoAsync(intUserId, intSchemeId, strValue, null);
        }
        
        /// <remarks/>
        public void BreedAutoAsync(int intUserId, int intSchemeId, string strValue, object userState) {
            if ((this.BreedAutoOperationCompleted == null)) {
                this.BreedAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBreedAutoOperationCompleted);
            }
            this.InvokeAsync("BreedAuto", new object[] {
                        intUserId,
                        intSchemeId,
                        strValue}, this.BreedAutoOperationCompleted, userState);
        }
        
        private void OnBreedAutoOperationCompleted(object arg) {
            if ((this.BreedAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BreedAutoCompleted(this, new BreedAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShedAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ShedAuto(string strValue) {
            object[] results = this.Invoke("ShedAuto", new object[] {
                        strValue});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ShedAutoAsync(string strValue) {
            this.ShedAutoAsync(strValue, null);
        }
        
        /// <remarks/>
        public void ShedAutoAsync(string strValue, object userState) {
            if ((this.ShedAutoOperationCompleted == null)) {
                this.ShedAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShedAutoOperationCompleted);
            }
            this.InvokeAsync("ShedAuto", new object[] {
                        strValue}, this.ShedAutoOperationCompleted, userState);
        }
        
        private void OnShedAutoOperationCompleted(object arg) {
            if ((this.ShedAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShedAutoCompleted(this, new ShedAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PenAuto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PenAuto(int intShedId, string strValue) {
            object[] results = this.Invoke("PenAuto", new object[] {
                        intShedId,
                        strValue});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PenAutoAsync(int intShedId, string strValue) {
            this.PenAutoAsync(intShedId, strValue, null);
        }
        
        /// <remarks/>
        public void PenAutoAsync(int intShedId, string strValue, object userState) {
            if ((this.PenAutoOperationCompleted == null)) {
                this.PenAutoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPenAutoOperationCompleted);
            }
            this.InvokeAsync("PenAuto", new object[] {
                        intShedId,
                        strValue}, this.PenAutoOperationCompleted, userState);
        }
        
        private void OnPenAutoOperationCompleted(object arg) {
            if ((this.PenAutoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PenAutoCompleted(this, new PenAutoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatusRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] StatusRetrieve() {
            object[] results = this.Invoke("StatusRetrieve", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void StatusRetrieveAsync() {
            this.StatusRetrieveAsync(null);
        }
        
        /// <remarks/>
        public void StatusRetrieveAsync(object userState) {
            if ((this.StatusRetrieveOperationCompleted == null)) {
                this.StatusRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatusRetrieveOperationCompleted);
            }
            this.InvokeAsync("StatusRetrieve", new object[0], this.StatusRetrieveOperationCompleted, userState);
        }
        
        private void OnStatusRetrieveOperationCompleted(object arg) {
            if ((this.StatusRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatusRetrieveCompleted(this, new StatusRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MatingStatusRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] MatingStatusRetrieve() {
            object[] results = this.Invoke("MatingStatusRetrieve", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void MatingStatusRetrieveAsync() {
            this.MatingStatusRetrieveAsync(null);
        }
        
        /// <remarks/>
        public void MatingStatusRetrieveAsync(object userState) {
            if ((this.MatingStatusRetrieveOperationCompleted == null)) {
                this.MatingStatusRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMatingStatusRetrieveOperationCompleted);
            }
            this.InvokeAsync("MatingStatusRetrieve", new object[0], this.MatingStatusRetrieveOperationCompleted, userState);
        }
        
        private void OnMatingStatusRetrieveOperationCompleted(object arg) {
            if ((this.MatingStatusRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MatingStatusRetrieveCompleted(this, new MatingStatusRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TagnoCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TagnoCheck(string strTagno) {
            object[] results = this.Invoke("TagnoCheck", new object[] {
                        strTagno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TagnoCheckAsync(string strTagno) {
            this.TagnoCheckAsync(strTagno, null);
        }
        
        /// <remarks/>
        public void TagnoCheckAsync(string strTagno, object userState) {
            if ((this.TagnoCheckOperationCompleted == null)) {
                this.TagnoCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTagnoCheckOperationCompleted);
            }
            this.InvokeAsync("TagnoCheck", new object[] {
                        strTagno}, this.TagnoCheckOperationCompleted, userState);
        }
        
        private void OnTagnoCheckOperationCompleted(object arg) {
            if ((this.TagnoCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TagnoCheckCompleted(this, new TagnoCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PigDetailUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PigDetailUpdate() {
            this.Invoke("PigDetailUpdate", new object[0]);
        }
        
        /// <remarks/>
        public void PigDetailUpdateAsync() {
            this.PigDetailUpdateAsync(null);
        }
        
        /// <remarks/>
        public void PigDetailUpdateAsync(object userState) {
            if ((this.PigDetailUpdateOperationCompleted == null)) {
                this.PigDetailUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPigDetailUpdateOperationCompleted);
            }
            this.InvokeAsync("PigDetailUpdate", new object[0], this.PigDetailUpdateOperationCompleted, userState);
        }
        
        private void OnPigDetailUpdateOperationCompleted(object arg) {
            if ((this.PigDetailUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PigDetailUpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WeightRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] WeightRetrieve() {
            object[] results = this.Invoke("WeightRetrieve", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void WeightRetrieveAsync() {
            this.WeightRetrieveAsync(null);
        }
        
        /// <remarks/>
        public void WeightRetrieveAsync(object userState) {
            if ((this.WeightRetrieveOperationCompleted == null)) {
                this.WeightRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWeightRetrieveOperationCompleted);
            }
            this.InvokeAsync("WeightRetrieve", new object[0], this.WeightRetrieveOperationCompleted, userState);
        }
        
        private void OnWeightRetrieveOperationCompleted(object arg) {
            if ((this.WeightRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WeightRetrieveCompleted(this, new WeightRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StageRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] StageRetrieve(int intId) {
            object[] results = this.Invoke("StageRetrieve", new object[] {
                        intId});
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void StageRetrieveAsync(int intId) {
            this.StageRetrieveAsync(intId, null);
        }
        
        /// <remarks/>
        public void StageRetrieveAsync(int intId, object userState) {
            if ((this.StageRetrieveOperationCompleted == null)) {
                this.StageRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStageRetrieveOperationCompleted);
            }
            this.InvokeAsync("StageRetrieve", new object[] {
                        intId}, this.StageRetrieveOperationCompleted, userState);
        }
        
        private void OnStageRetrieveOperationCompleted(object arg) {
            if ((this.StageRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StageRetrieveCompleted(this, new StageRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PigListRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PigList[] PigListRetrieve(PigList pl) {
            object[] results = this.Invoke("PigListRetrieve", new object[] {
                        pl});
            return ((PigList[])(results[0]));
        }
        
        /// <remarks/>
        public void PigListRetrieveAsync(PigList pl) {
            this.PigListRetrieveAsync(pl, null);
        }
        
        /// <remarks/>
        public void PigListRetrieveAsync(PigList pl, object userState) {
            if ((this.PigListRetrieveOperationCompleted == null)) {
                this.PigListRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPigListRetrieveOperationCompleted);
            }
            this.InvokeAsync("PigListRetrieve", new object[] {
                        pl}, this.PigListRetrieveOperationCompleted, userState);
        }
        
        private void OnPigListRetrieveOperationCompleted(object arg) {
            if ((this.PigListRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PigListRetrieveCompleted(this, new PigListRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GroupBasedStatusRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] GroupBasedStatusRetrieve(int intGroupId) {
            object[] results = this.Invoke("GroupBasedStatusRetrieve", new object[] {
                        intGroupId});
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void GroupBasedStatusRetrieveAsync(int intGroupId) {
            this.GroupBasedStatusRetrieveAsync(intGroupId, null);
        }
        
        /// <remarks/>
        public void GroupBasedStatusRetrieveAsync(int intGroupId, object userState) {
            if ((this.GroupBasedStatusRetrieveOperationCompleted == null)) {
                this.GroupBasedStatusRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupBasedStatusRetrieveOperationCompleted);
            }
            this.InvokeAsync("GroupBasedStatusRetrieve", new object[] {
                        intGroupId}, this.GroupBasedStatusRetrieveOperationCompleted, userState);
        }
        
        private void OnGroupBasedStatusRetrieveOperationCompleted(object arg) {
            if ((this.GroupBasedStatusRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupBasedStatusRetrieveCompleted(this, new GroupBasedStatusRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MetaData {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PigList {
        
        private string idField;
        
        private string tagnoField;
        
        private string schemeField;
        
        private string breedField;
        
        private string sexField;
        
        private string birthDateField;
        
        private string sirenoField;
        
        private string damnoField;
        
        private string noofFarrowingField;
        
        private string noofPigletsField;
        
        private string statusField;
        
        private string shednoField;
        
        private string pennoField;
        
        private int userIdField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Tagno {
            get {
                return this.tagnoField;
            }
            set {
                this.tagnoField = value;
            }
        }
        
        /// <remarks/>
        public string Scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string Sireno {
            get {
                return this.sirenoField;
            }
            set {
                this.sirenoField = value;
            }
        }
        
        /// <remarks/>
        public string Damno {
            get {
                return this.damnoField;
            }
            set {
                this.damnoField = value;
            }
        }
        
        /// <remarks/>
        public string NoofFarrowing {
            get {
                return this.noofFarrowingField;
            }
            set {
                this.noofFarrowingField = value;
            }
        }
        
        /// <remarks/>
        public string NoofPiglets {
            get {
                return this.noofPigletsField;
            }
            set {
                this.noofPigletsField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Shedno {
            get {
                return this.shednoField;
            }
            set {
                this.shednoField = value;
            }
        }
        
        /// <remarks/>
        public string Penno {
            get {
                return this.pennoField;
            }
            set {
                this.pennoField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TagnoAutoCompletedEventHandler(object sender, TagnoAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TagnoAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TagnoAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SchemeAutoCompletedEventHandler(object sender, SchemeAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SchemeAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SchemeAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BreedAutoCompletedEventHandler(object sender, BreedAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BreedAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BreedAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ShedAutoCompletedEventHandler(object sender, ShedAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShedAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShedAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PenAutoCompletedEventHandler(object sender, PenAutoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PenAutoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PenAutoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StatusRetrieveCompletedEventHandler(object sender, StatusRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatusRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MatingStatusRetrieveCompletedEventHandler(object sender, MatingStatusRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MatingStatusRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MatingStatusRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TagnoCheckCompletedEventHandler(object sender, TagnoCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TagnoCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TagnoCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PigDetailUpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void WeightRetrieveCompletedEventHandler(object sender, WeightRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeightRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WeightRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StageRetrieveCompletedEventHandler(object sender, StageRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StageRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StageRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PigListRetrieveCompletedEventHandler(object sender, PigListRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PigListRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PigListRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PigList[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PigList[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GroupBasedStatusRetrieveCompletedEventHandler(object sender, GroupBasedStatusRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupBasedStatusRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupBasedStatusRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591