//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PMS.PMS_Reports {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PMS_ReportsSoap", Namespace="http://tempuri.org/")]
    public partial class PMS_Reports : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StockReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback FeedReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PurchaseReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SellingReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeathReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback DailyStockReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback EconomicIndicesReportRetrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback PigGenerationRetrieveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PMS_Reports() {
            this.Url = global::PMS.Properties.Settings.Default.PMS_PMS_Reports_PMS_Reports;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StockReportRetrieveCompletedEventHandler StockReportRetrieveCompleted;
        
        /// <remarks/>
        public event FeedReportRetrieveCompletedEventHandler FeedReportRetrieveCompleted;
        
        /// <remarks/>
        public event PurchaseReportRetrieveCompletedEventHandler PurchaseReportRetrieveCompleted;
        
        /// <remarks/>
        public event SellingReportRetrieveCompletedEventHandler SellingReportRetrieveCompleted;
        
        /// <remarks/>
        public event DeathReportRetrieveCompletedEventHandler DeathReportRetrieveCompleted;
        
        /// <remarks/>
        public event DailyStockReportRetrieveCompletedEventHandler DailyStockReportRetrieveCompleted;
        
        /// <remarks/>
        public event EconomicIndicesReportRetrieveCompletedEventHandler EconomicIndicesReportRetrieveCompleted;
        
        /// <remarks/>
        public event PigGenerationRetrieveCompletedEventHandler PigGenerationRetrieveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StockReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockReport[] StockReportRetrieve(StockReport sr) {
            object[] results = this.Invoke("StockReportRetrieve", new object[] {
                        sr});
            return ((StockReport[])(results[0]));
        }
        
        /// <remarks/>
        public void StockReportRetrieveAsync(StockReport sr) {
            this.StockReportRetrieveAsync(sr, null);
        }
        
        /// <remarks/>
        public void StockReportRetrieveAsync(StockReport sr, object userState) {
            if ((this.StockReportRetrieveOperationCompleted == null)) {
                this.StockReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStockReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("StockReportRetrieve", new object[] {
                        sr}, this.StockReportRetrieveOperationCompleted, userState);
        }
        
        private void OnStockReportRetrieveOperationCompleted(object arg) {
            if ((this.StockReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StockReportRetrieveCompleted(this, new StockReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FeedReport[] FeedReportRetrieve(FeedReport fr) {
            object[] results = this.Invoke("FeedReportRetrieve", new object[] {
                        fr});
            return ((FeedReport[])(results[0]));
        }
        
        /// <remarks/>
        public void FeedReportRetrieveAsync(FeedReport fr) {
            this.FeedReportRetrieveAsync(fr, null);
        }
        
        /// <remarks/>
        public void FeedReportRetrieveAsync(FeedReport fr, object userState) {
            if ((this.FeedReportRetrieveOperationCompleted == null)) {
                this.FeedReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeedReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("FeedReportRetrieve", new object[] {
                        fr}, this.FeedReportRetrieveOperationCompleted, userState);
        }
        
        private void OnFeedReportRetrieveOperationCompleted(object arg) {
            if ((this.FeedReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeedReportRetrieveCompleted(this, new FeedReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PurchaseReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PurchaseReport[] PurchaseReportRetrieve(PurchaseReport pr) {
            object[] results = this.Invoke("PurchaseReportRetrieve", new object[] {
                        pr});
            return ((PurchaseReport[])(results[0]));
        }
        
        /// <remarks/>
        public void PurchaseReportRetrieveAsync(PurchaseReport pr) {
            this.PurchaseReportRetrieveAsync(pr, null);
        }
        
        /// <remarks/>
        public void PurchaseReportRetrieveAsync(PurchaseReport pr, object userState) {
            if ((this.PurchaseReportRetrieveOperationCompleted == null)) {
                this.PurchaseReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPurchaseReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("PurchaseReportRetrieve", new object[] {
                        pr}, this.PurchaseReportRetrieveOperationCompleted, userState);
        }
        
        private void OnPurchaseReportRetrieveOperationCompleted(object arg) {
            if ((this.PurchaseReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PurchaseReportRetrieveCompleted(this, new PurchaseReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SellingReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SellingReport[] SellingReportRetrieve(SellingReport sr) {
            object[] results = this.Invoke("SellingReportRetrieve", new object[] {
                        sr});
            return ((SellingReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SellingReportRetrieveAsync(SellingReport sr) {
            this.SellingReportRetrieveAsync(sr, null);
        }
        
        /// <remarks/>
        public void SellingReportRetrieveAsync(SellingReport sr, object userState) {
            if ((this.SellingReportRetrieveOperationCompleted == null)) {
                this.SellingReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellingReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("SellingReportRetrieve", new object[] {
                        sr}, this.SellingReportRetrieveOperationCompleted, userState);
        }
        
        private void OnSellingReportRetrieveOperationCompleted(object arg) {
            if ((this.SellingReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellingReportRetrieveCompleted(this, new SellingReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeathReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeathReport[] DeathReportRetrieve(DeathReport dr) {
            object[] results = this.Invoke("DeathReportRetrieve", new object[] {
                        dr});
            return ((DeathReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeathReportRetrieveAsync(DeathReport dr) {
            this.DeathReportRetrieveAsync(dr, null);
        }
        
        /// <remarks/>
        public void DeathReportRetrieveAsync(DeathReport dr, object userState) {
            if ((this.DeathReportRetrieveOperationCompleted == null)) {
                this.DeathReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeathReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("DeathReportRetrieve", new object[] {
                        dr}, this.DeathReportRetrieveOperationCompleted, userState);
        }
        
        private void OnDeathReportRetrieveOperationCompleted(object arg) {
            if ((this.DeathReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeathReportRetrieveCompleted(this, new DeathReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DailyStockReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DailyStockReport[] DailyStockReportRetrieve(DailyStockReport dsr) {
            object[] results = this.Invoke("DailyStockReportRetrieve", new object[] {
                        dsr});
            return ((DailyStockReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DailyStockReportRetrieveAsync(DailyStockReport dsr) {
            this.DailyStockReportRetrieveAsync(dsr, null);
        }
        
        /// <remarks/>
        public void DailyStockReportRetrieveAsync(DailyStockReport dsr, object userState) {
            if ((this.DailyStockReportRetrieveOperationCompleted == null)) {
                this.DailyStockReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDailyStockReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("DailyStockReportRetrieve", new object[] {
                        dsr}, this.DailyStockReportRetrieveOperationCompleted, userState);
        }
        
        private void OnDailyStockReportRetrieveOperationCompleted(object arg) {
            if ((this.DailyStockReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DailyStockReportRetrieveCompleted(this, new DailyStockReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EconomicIndicesReportRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EconomicIndicesReport[] EconomicIndicesReportRetrieve(int intSchemeId, int intFy) {
            object[] results = this.Invoke("EconomicIndicesReportRetrieve", new object[] {
                        intSchemeId,
                        intFy});
            return ((EconomicIndicesReport[])(results[0]));
        }
        
        /// <remarks/>
        public void EconomicIndicesReportRetrieveAsync(int intSchemeId, int intFy) {
            this.EconomicIndicesReportRetrieveAsync(intSchemeId, intFy, null);
        }
        
        /// <remarks/>
        public void EconomicIndicesReportRetrieveAsync(int intSchemeId, int intFy, object userState) {
            if ((this.EconomicIndicesReportRetrieveOperationCompleted == null)) {
                this.EconomicIndicesReportRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEconomicIndicesReportRetrieveOperationCompleted);
            }
            this.InvokeAsync("EconomicIndicesReportRetrieve", new object[] {
                        intSchemeId,
                        intFy}, this.EconomicIndicesReportRetrieveOperationCompleted, userState);
        }
        
        private void OnEconomicIndicesReportRetrieveOperationCompleted(object arg) {
            if ((this.EconomicIndicesReportRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EconomicIndicesReportRetrieveCompleted(this, new EconomicIndicesReportRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PigGenerationRetrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PigGenerationRetrieve(string strTagNo) {
            object[] results = this.Invoke("PigGenerationRetrieve", new object[] {
                        strTagNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PigGenerationRetrieveAsync(string strTagNo) {
            this.PigGenerationRetrieveAsync(strTagNo, null);
        }
        
        /// <remarks/>
        public void PigGenerationRetrieveAsync(string strTagNo, object userState) {
            if ((this.PigGenerationRetrieveOperationCompleted == null)) {
                this.PigGenerationRetrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPigGenerationRetrieveOperationCompleted);
            }
            this.InvokeAsync("PigGenerationRetrieve", new object[] {
                        strTagNo}, this.PigGenerationRetrieveOperationCompleted, userState);
        }
        
        private void OnPigGenerationRetrieveOperationCompleted(object arg) {
            if ((this.PigGenerationRetrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PigGenerationRetrieveCompleted(this, new PigGenerationRetrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockReport {
        
        private int schemeIdField;
        
        private int breedIdField;
        
        private int reportTypeField;
        
        private string stockMonthField;
        
        private string stockYearField;
        
        private string dateField;
        
        private string oBAMField;
        
        private string oBAFField;
        
        private string oBGMField;
        
        private string oBGFField;
        
        private string oBSMField;
        
        private string oBSFField;
        
        private string oBTMField;
        
        private string oBTFField;
        
        private string oBGTField;
        
        private string bSMField;
        
        private string bSFField;
        
        private string pAMField;
        
        private string pAFField;
        
        private string pGMField;
        
        private string pGFField;
        
        private string bSAMField;
        
        private string bSAFField;
        
        private string bSGMField;
        
        private string bSGFField;
        
        private string sSAMField;
        
        private string sSAFField;
        
        private string sSGMField;
        
        private string sSGFField;
        
        private string dAMField;
        
        private string dAFField;
        
        private string dGMField;
        
        private string dGFField;
        
        private string dSMField;
        
        private string dSFField;
        
        private string iTAMField;
        
        private string iTAFField;
        
        private string iTGMField;
        
        private string iTGFField;
        
        private string iTSMField;
        
        private string iTSFField;
        
        private string cBAMField;
        
        private string cBAFField;
        
        private string cBGMField;
        
        private string cBGFField;
        
        private string cBSMField;
        
        private string cBSFField;
        
        private string cBTMField;
        
        private string cBTFField;
        
        private string cBGTField;
        
        /// <remarks/>
        public int SchemeId {
            get {
                return this.schemeIdField;
            }
            set {
                this.schemeIdField = value;
            }
        }
        
        /// <remarks/>
        public int BreedId {
            get {
                return this.breedIdField;
            }
            set {
                this.breedIdField = value;
            }
        }
        
        /// <remarks/>
        public int ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string StockMonth {
            get {
                return this.stockMonthField;
            }
            set {
                this.stockMonthField = value;
            }
        }
        
        /// <remarks/>
        public string StockYear {
            get {
                return this.stockYearField;
            }
            set {
                this.stockYearField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string OBAM {
            get {
                return this.oBAMField;
            }
            set {
                this.oBAMField = value;
            }
        }
        
        /// <remarks/>
        public string OBAF {
            get {
                return this.oBAFField;
            }
            set {
                this.oBAFField = value;
            }
        }
        
        /// <remarks/>
        public string OBGM {
            get {
                return this.oBGMField;
            }
            set {
                this.oBGMField = value;
            }
        }
        
        /// <remarks/>
        public string OBGF {
            get {
                return this.oBGFField;
            }
            set {
                this.oBGFField = value;
            }
        }
        
        /// <remarks/>
        public string OBSM {
            get {
                return this.oBSMField;
            }
            set {
                this.oBSMField = value;
            }
        }
        
        /// <remarks/>
        public string OBSF {
            get {
                return this.oBSFField;
            }
            set {
                this.oBSFField = value;
            }
        }
        
        /// <remarks/>
        public string OBTM {
            get {
                return this.oBTMField;
            }
            set {
                this.oBTMField = value;
            }
        }
        
        /// <remarks/>
        public string OBTF {
            get {
                return this.oBTFField;
            }
            set {
                this.oBTFField = value;
            }
        }
        
        /// <remarks/>
        public string OBGT {
            get {
                return this.oBGTField;
            }
            set {
                this.oBGTField = value;
            }
        }
        
        /// <remarks/>
        public string BSM {
            get {
                return this.bSMField;
            }
            set {
                this.bSMField = value;
            }
        }
        
        /// <remarks/>
        public string BSF {
            get {
                return this.bSFField;
            }
            set {
                this.bSFField = value;
            }
        }
        
        /// <remarks/>
        public string PAM {
            get {
                return this.pAMField;
            }
            set {
                this.pAMField = value;
            }
        }
        
        /// <remarks/>
        public string PAF {
            get {
                return this.pAFField;
            }
            set {
                this.pAFField = value;
            }
        }
        
        /// <remarks/>
        public string PGM {
            get {
                return this.pGMField;
            }
            set {
                this.pGMField = value;
            }
        }
        
        /// <remarks/>
        public string PGF {
            get {
                return this.pGFField;
            }
            set {
                this.pGFField = value;
            }
        }
        
        /// <remarks/>
        public string BSAM {
            get {
                return this.bSAMField;
            }
            set {
                this.bSAMField = value;
            }
        }
        
        /// <remarks/>
        public string BSAF {
            get {
                return this.bSAFField;
            }
            set {
                this.bSAFField = value;
            }
        }
        
        /// <remarks/>
        public string BSGM {
            get {
                return this.bSGMField;
            }
            set {
                this.bSGMField = value;
            }
        }
        
        /// <remarks/>
        public string BSGF {
            get {
                return this.bSGFField;
            }
            set {
                this.bSGFField = value;
            }
        }
        
        /// <remarks/>
        public string SSAM {
            get {
                return this.sSAMField;
            }
            set {
                this.sSAMField = value;
            }
        }
        
        /// <remarks/>
        public string SSAF {
            get {
                return this.sSAFField;
            }
            set {
                this.sSAFField = value;
            }
        }
        
        /// <remarks/>
        public string SSGM {
            get {
                return this.sSGMField;
            }
            set {
                this.sSGMField = value;
            }
        }
        
        /// <remarks/>
        public string SSGF {
            get {
                return this.sSGFField;
            }
            set {
                this.sSGFField = value;
            }
        }
        
        /// <remarks/>
        public string DAM {
            get {
                return this.dAMField;
            }
            set {
                this.dAMField = value;
            }
        }
        
        /// <remarks/>
        public string DAF {
            get {
                return this.dAFField;
            }
            set {
                this.dAFField = value;
            }
        }
        
        /// <remarks/>
        public string DGM {
            get {
                return this.dGMField;
            }
            set {
                this.dGMField = value;
            }
        }
        
        /// <remarks/>
        public string DGF {
            get {
                return this.dGFField;
            }
            set {
                this.dGFField = value;
            }
        }
        
        /// <remarks/>
        public string DSM {
            get {
                return this.dSMField;
            }
            set {
                this.dSMField = value;
            }
        }
        
        /// <remarks/>
        public string DSF {
            get {
                return this.dSFField;
            }
            set {
                this.dSFField = value;
            }
        }
        
        /// <remarks/>
        public string ITAM {
            get {
                return this.iTAMField;
            }
            set {
                this.iTAMField = value;
            }
        }
        
        /// <remarks/>
        public string ITAF {
            get {
                return this.iTAFField;
            }
            set {
                this.iTAFField = value;
            }
        }
        
        /// <remarks/>
        public string ITGM {
            get {
                return this.iTGMField;
            }
            set {
                this.iTGMField = value;
            }
        }
        
        /// <remarks/>
        public string ITGF {
            get {
                return this.iTGFField;
            }
            set {
                this.iTGFField = value;
            }
        }
        
        /// <remarks/>
        public string ITSM {
            get {
                return this.iTSMField;
            }
            set {
                this.iTSMField = value;
            }
        }
        
        /// <remarks/>
        public string ITSF {
            get {
                return this.iTSFField;
            }
            set {
                this.iTSFField = value;
            }
        }
        
        /// <remarks/>
        public string CBAM {
            get {
                return this.cBAMField;
            }
            set {
                this.cBAMField = value;
            }
        }
        
        /// <remarks/>
        public string CBAF {
            get {
                return this.cBAFField;
            }
            set {
                this.cBAFField = value;
            }
        }
        
        /// <remarks/>
        public string CBGM {
            get {
                return this.cBGMField;
            }
            set {
                this.cBGMField = value;
            }
        }
        
        /// <remarks/>
        public string CBGF {
            get {
                return this.cBGFField;
            }
            set {
                this.cBGFField = value;
            }
        }
        
        /// <remarks/>
        public string CBSM {
            get {
                return this.cBSMField;
            }
            set {
                this.cBSMField = value;
            }
        }
        
        /// <remarks/>
        public string CBSF {
            get {
                return this.cBSFField;
            }
            set {
                this.cBSFField = value;
            }
        }
        
        /// <remarks/>
        public string CBTM {
            get {
                return this.cBTMField;
            }
            set {
                this.cBTMField = value;
            }
        }
        
        /// <remarks/>
        public string CBTF {
            get {
                return this.cBTFField;
            }
            set {
                this.cBTFField = value;
            }
        }
        
        /// <remarks/>
        public string CBGT {
            get {
                return this.cBGTField;
            }
            set {
                this.cBGTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EconomicIndicesReport {
        
        private string feedCostField;
        
        private string swillCostField;
        
        private string otherCostField;
        
        private string veterinaryChargesField;
        
        private string electricityChargesField;
        
        private string labourCostField;
        
        private string variableanyOtherField;
        
        private string variableOthersField;
        
        private string totalCostField;
        
        private string animalSaleField;
        
        private string meatSaleField;
        
        private string manureSaleField;
        
        private string gunnySaleField;
        
        private string receiptAnyOtherField;
        
        private string receiptOthersField;
        
        private string totalReceiptsCostField;
        
        private string nRVCField;
        
        private string nRVCPerField;
        
        private string nRFCField;
        
        private string nRFCPerField;
        
        private string cOPLiveBodyField;
        
        private string netFarmincomeField;
        
        private string netMarketValueField;
        
        private string cOPPigletField;
        
        private string aDGBWField;
        
        private string aDGWMField;
        
        private string nOPPField;
        
        private string nOPMField;
        
        /// <remarks/>
        public string FeedCost {
            get {
                return this.feedCostField;
            }
            set {
                this.feedCostField = value;
            }
        }
        
        /// <remarks/>
        public string SwillCost {
            get {
                return this.swillCostField;
            }
            set {
                this.swillCostField = value;
            }
        }
        
        /// <remarks/>
        public string OtherCost {
            get {
                return this.otherCostField;
            }
            set {
                this.otherCostField = value;
            }
        }
        
        /// <remarks/>
        public string VeterinaryCharges {
            get {
                return this.veterinaryChargesField;
            }
            set {
                this.veterinaryChargesField = value;
            }
        }
        
        /// <remarks/>
        public string ElectricityCharges {
            get {
                return this.electricityChargesField;
            }
            set {
                this.electricityChargesField = value;
            }
        }
        
        /// <remarks/>
        public string LabourCost {
            get {
                return this.labourCostField;
            }
            set {
                this.labourCostField = value;
            }
        }
        
        /// <remarks/>
        public string VariableanyOther {
            get {
                return this.variableanyOtherField;
            }
            set {
                this.variableanyOtherField = value;
            }
        }
        
        /// <remarks/>
        public string VariableOthers {
            get {
                return this.variableOthersField;
            }
            set {
                this.variableOthersField = value;
            }
        }
        
        /// <remarks/>
        public string TotalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
            }
        }
        
        /// <remarks/>
        public string AnimalSale {
            get {
                return this.animalSaleField;
            }
            set {
                this.animalSaleField = value;
            }
        }
        
        /// <remarks/>
        public string MeatSale {
            get {
                return this.meatSaleField;
            }
            set {
                this.meatSaleField = value;
            }
        }
        
        /// <remarks/>
        public string ManureSale {
            get {
                return this.manureSaleField;
            }
            set {
                this.manureSaleField = value;
            }
        }
        
        /// <remarks/>
        public string GunnySale {
            get {
                return this.gunnySaleField;
            }
            set {
                this.gunnySaleField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptAnyOther {
            get {
                return this.receiptAnyOtherField;
            }
            set {
                this.receiptAnyOtherField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptOthers {
            get {
                return this.receiptOthersField;
            }
            set {
                this.receiptOthersField = value;
            }
        }
        
        /// <remarks/>
        public string TotalReceiptsCost {
            get {
                return this.totalReceiptsCostField;
            }
            set {
                this.totalReceiptsCostField = value;
            }
        }
        
        /// <remarks/>
        public string NRVC {
            get {
                return this.nRVCField;
            }
            set {
                this.nRVCField = value;
            }
        }
        
        /// <remarks/>
        public string NRVCPer {
            get {
                return this.nRVCPerField;
            }
            set {
                this.nRVCPerField = value;
            }
        }
        
        /// <remarks/>
        public string NRFC {
            get {
                return this.nRFCField;
            }
            set {
                this.nRFCField = value;
            }
        }
        
        /// <remarks/>
        public string NRFCPer {
            get {
                return this.nRFCPerField;
            }
            set {
                this.nRFCPerField = value;
            }
        }
        
        /// <remarks/>
        public string COPLiveBody {
            get {
                return this.cOPLiveBodyField;
            }
            set {
                this.cOPLiveBodyField = value;
            }
        }
        
        /// <remarks/>
        public string NetFarmincome {
            get {
                return this.netFarmincomeField;
            }
            set {
                this.netFarmincomeField = value;
            }
        }
        
        /// <remarks/>
        public string NetMarketValue {
            get {
                return this.netMarketValueField;
            }
            set {
                this.netMarketValueField = value;
            }
        }
        
        /// <remarks/>
        public string COPPiglet {
            get {
                return this.cOPPigletField;
            }
            set {
                this.cOPPigletField = value;
            }
        }
        
        /// <remarks/>
        public string ADGBW {
            get {
                return this.aDGBWField;
            }
            set {
                this.aDGBWField = value;
            }
        }
        
        /// <remarks/>
        public string ADGWM {
            get {
                return this.aDGWMField;
            }
            set {
                this.aDGWMField = value;
            }
        }
        
        /// <remarks/>
        public string NOPP {
            get {
                return this.nOPPField;
            }
            set {
                this.nOPPField = value;
            }
        }
        
        /// <remarks/>
        public string NOPM {
            get {
                return this.nOPMField;
            }
            set {
                this.nOPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyStockReport {
        
        private int schemeIdField;
        
        private int breedIdField;
        
        private string dateField;
        
        private string oBAMField;
        
        private string oBAFField;
        
        private string oBGMField;
        
        private string oBGFField;
        
        private string oBSMField;
        
        private string oBSFField;
        
        private string oBTMField;
        
        private string oBTFField;
        
        private string oBGTField;
        
        private string bSMField;
        
        private string bSFField;
        
        private string pAMField;
        
        private string pAFField;
        
        private string pGMField;
        
        private string pGFField;
        
        private string bSAMField;
        
        private string bSAFField;
        
        private string bSGMField;
        
        private string bSGFField;
        
        private string sSAMField;
        
        private string sSAFField;
        
        private string sSGMField;
        
        private string sSGFField;
        
        private string dAMField;
        
        private string dAFField;
        
        private string dGMField;
        
        private string dGFField;
        
        private string dSMField;
        
        private string dSFField;
        
        private string iTAMField;
        
        private string iTAFField;
        
        private string iTGMField;
        
        private string iTGFField;
        
        private string iTSMField;
        
        private string iTSFField;
        
        private string cBAMField;
        
        private string cBAFField;
        
        private string cBGMField;
        
        private string cBGFField;
        
        private string cBSMField;
        
        private string cBSFField;
        
        private string cBTMField;
        
        private string cBTFField;
        
        private string cBGTField;
        
        /// <remarks/>
        public int SchemeId {
            get {
                return this.schemeIdField;
            }
            set {
                this.schemeIdField = value;
            }
        }
        
        /// <remarks/>
        public int BreedId {
            get {
                return this.breedIdField;
            }
            set {
                this.breedIdField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string OBAM {
            get {
                return this.oBAMField;
            }
            set {
                this.oBAMField = value;
            }
        }
        
        /// <remarks/>
        public string OBAF {
            get {
                return this.oBAFField;
            }
            set {
                this.oBAFField = value;
            }
        }
        
        /// <remarks/>
        public string OBGM {
            get {
                return this.oBGMField;
            }
            set {
                this.oBGMField = value;
            }
        }
        
        /// <remarks/>
        public string OBGF {
            get {
                return this.oBGFField;
            }
            set {
                this.oBGFField = value;
            }
        }
        
        /// <remarks/>
        public string OBSM {
            get {
                return this.oBSMField;
            }
            set {
                this.oBSMField = value;
            }
        }
        
        /// <remarks/>
        public string OBSF {
            get {
                return this.oBSFField;
            }
            set {
                this.oBSFField = value;
            }
        }
        
        /// <remarks/>
        public string OBTM {
            get {
                return this.oBTMField;
            }
            set {
                this.oBTMField = value;
            }
        }
        
        /// <remarks/>
        public string OBTF {
            get {
                return this.oBTFField;
            }
            set {
                this.oBTFField = value;
            }
        }
        
        /// <remarks/>
        public string OBGT {
            get {
                return this.oBGTField;
            }
            set {
                this.oBGTField = value;
            }
        }
        
        /// <remarks/>
        public string BSM {
            get {
                return this.bSMField;
            }
            set {
                this.bSMField = value;
            }
        }
        
        /// <remarks/>
        public string BSF {
            get {
                return this.bSFField;
            }
            set {
                this.bSFField = value;
            }
        }
        
        /// <remarks/>
        public string PAM {
            get {
                return this.pAMField;
            }
            set {
                this.pAMField = value;
            }
        }
        
        /// <remarks/>
        public string PAF {
            get {
                return this.pAFField;
            }
            set {
                this.pAFField = value;
            }
        }
        
        /// <remarks/>
        public string PGM {
            get {
                return this.pGMField;
            }
            set {
                this.pGMField = value;
            }
        }
        
        /// <remarks/>
        public string PGF {
            get {
                return this.pGFField;
            }
            set {
                this.pGFField = value;
            }
        }
        
        /// <remarks/>
        public string BSAM {
            get {
                return this.bSAMField;
            }
            set {
                this.bSAMField = value;
            }
        }
        
        /// <remarks/>
        public string BSAF {
            get {
                return this.bSAFField;
            }
            set {
                this.bSAFField = value;
            }
        }
        
        /// <remarks/>
        public string BSGM {
            get {
                return this.bSGMField;
            }
            set {
                this.bSGMField = value;
            }
        }
        
        /// <remarks/>
        public string BSGF {
            get {
                return this.bSGFField;
            }
            set {
                this.bSGFField = value;
            }
        }
        
        /// <remarks/>
        public string SSAM {
            get {
                return this.sSAMField;
            }
            set {
                this.sSAMField = value;
            }
        }
        
        /// <remarks/>
        public string SSAF {
            get {
                return this.sSAFField;
            }
            set {
                this.sSAFField = value;
            }
        }
        
        /// <remarks/>
        public string SSGM {
            get {
                return this.sSGMField;
            }
            set {
                this.sSGMField = value;
            }
        }
        
        /// <remarks/>
        public string SSGF {
            get {
                return this.sSGFField;
            }
            set {
                this.sSGFField = value;
            }
        }
        
        /// <remarks/>
        public string DAM {
            get {
                return this.dAMField;
            }
            set {
                this.dAMField = value;
            }
        }
        
        /// <remarks/>
        public string DAF {
            get {
                return this.dAFField;
            }
            set {
                this.dAFField = value;
            }
        }
        
        /// <remarks/>
        public string DGM {
            get {
                return this.dGMField;
            }
            set {
                this.dGMField = value;
            }
        }
        
        /// <remarks/>
        public string DGF {
            get {
                return this.dGFField;
            }
            set {
                this.dGFField = value;
            }
        }
        
        /// <remarks/>
        public string DSM {
            get {
                return this.dSMField;
            }
            set {
                this.dSMField = value;
            }
        }
        
        /// <remarks/>
        public string DSF {
            get {
                return this.dSFField;
            }
            set {
                this.dSFField = value;
            }
        }
        
        /// <remarks/>
        public string ITAM {
            get {
                return this.iTAMField;
            }
            set {
                this.iTAMField = value;
            }
        }
        
        /// <remarks/>
        public string ITAF {
            get {
                return this.iTAFField;
            }
            set {
                this.iTAFField = value;
            }
        }
        
        /// <remarks/>
        public string ITGM {
            get {
                return this.iTGMField;
            }
            set {
                this.iTGMField = value;
            }
        }
        
        /// <remarks/>
        public string ITGF {
            get {
                return this.iTGFField;
            }
            set {
                this.iTGFField = value;
            }
        }
        
        /// <remarks/>
        public string ITSM {
            get {
                return this.iTSMField;
            }
            set {
                this.iTSMField = value;
            }
        }
        
        /// <remarks/>
        public string ITSF {
            get {
                return this.iTSFField;
            }
            set {
                this.iTSFField = value;
            }
        }
        
        /// <remarks/>
        public string CBAM {
            get {
                return this.cBAMField;
            }
            set {
                this.cBAMField = value;
            }
        }
        
        /// <remarks/>
        public string CBAF {
            get {
                return this.cBAFField;
            }
            set {
                this.cBAFField = value;
            }
        }
        
        /// <remarks/>
        public string CBGM {
            get {
                return this.cBGMField;
            }
            set {
                this.cBGMField = value;
            }
        }
        
        /// <remarks/>
        public string CBGF {
            get {
                return this.cBGFField;
            }
            set {
                this.cBGFField = value;
            }
        }
        
        /// <remarks/>
        public string CBSM {
            get {
                return this.cBSMField;
            }
            set {
                this.cBSMField = value;
            }
        }
        
        /// <remarks/>
        public string CBSF {
            get {
                return this.cBSFField;
            }
            set {
                this.cBSFField = value;
            }
        }
        
        /// <remarks/>
        public string CBTM {
            get {
                return this.cBTMField;
            }
            set {
                this.cBTMField = value;
            }
        }
        
        /// <remarks/>
        public string CBTF {
            get {
                return this.cBTFField;
            }
            set {
                this.cBTFField = value;
            }
        }
        
        /// <remarks/>
        public string CBGT {
            get {
                return this.cBGTField;
            }
            set {
                this.cBGTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeathReport {
        
        private int schemeIdField;
        
        private int breedIdField;
        
        private int reportTypeField;
        
        private string deathMonthField;
        
        private string deathYearField;
        
        private string tagNoField;
        
        private string stageField;
        
        private string yearField;
        
        private string monthField;
        
        private string dayField;
        
        private string sexField;
        
        private string writeValueField;
        
        private string historyField;
        
        private string clinicalSignsField;
        
        private string grossLesionsField;
        
        private string materialSentField;
        
        private string tentativeDiagnosisField;
        
        /// <remarks/>
        public int SchemeId {
            get {
                return this.schemeIdField;
            }
            set {
                this.schemeIdField = value;
            }
        }
        
        /// <remarks/>
        public int BreedId {
            get {
                return this.breedIdField;
            }
            set {
                this.breedIdField = value;
            }
        }
        
        /// <remarks/>
        public int ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DeathMonth {
            get {
                return this.deathMonthField;
            }
            set {
                this.deathMonthField = value;
            }
        }
        
        /// <remarks/>
        public string DeathYear {
            get {
                return this.deathYearField;
            }
            set {
                this.deathYearField = value;
            }
        }
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public string Stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string WriteValue {
            get {
                return this.writeValueField;
            }
            set {
                this.writeValueField = value;
            }
        }
        
        /// <remarks/>
        public string History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
            }
        }
        
        /// <remarks/>
        public string ClinicalSigns {
            get {
                return this.clinicalSignsField;
            }
            set {
                this.clinicalSignsField = value;
            }
        }
        
        /// <remarks/>
        public string GrossLesions {
            get {
                return this.grossLesionsField;
            }
            set {
                this.grossLesionsField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialSent {
            get {
                return this.materialSentField;
            }
            set {
                this.materialSentField = value;
            }
        }
        
        /// <remarks/>
        public string TentativeDiagnosis {
            get {
                return this.tentativeDiagnosisField;
            }
            set {
                this.tentativeDiagnosisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SellingReport {
        
        private string statusIdField;
        
        private string sellingMonthField;
        
        private string sellingYearField;
        
        private int reportTypeField;
        
        private string dateField;
        
        private string tagNoField;
        
        private string schemeField;
        
        private string breedField;
        
        private string sexField;
        
        private string statusField;
        
        private string weightField;
        
        private string baseRateField;
        
        private string rateperKgField;
        
        private string amountField;
        
        private string receiptNoField;
        
        private string customerField;
        
        /// <remarks/>
        public string StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        public string SellingMonth {
            get {
                return this.sellingMonthField;
            }
            set {
                this.sellingMonthField = value;
            }
        }
        
        /// <remarks/>
        public string SellingYear {
            get {
                return this.sellingYearField;
            }
            set {
                this.sellingYearField = value;
            }
        }
        
        /// <remarks/>
        public int ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public string Scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string BaseRate {
            get {
                return this.baseRateField;
            }
            set {
                this.baseRateField = value;
            }
        }
        
        /// <remarks/>
        public string RateperKg {
            get {
                return this.rateperKgField;
            }
            set {
                this.rateperKgField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
            }
        }
        
        /// <remarks/>
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseReport {
        
        private string tagNoField;
        
        private string purchaseMonthField;
        
        private string purchaseYearField;
        
        private int reportTypeField;
        
        private string dateField;
        
        private string schemeField;
        
        private string breedField;
        
        private string sexField;
        
        private string purchaseWeightField;
        
        private string receiptNoField;
        
        private string amountField;
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseMonth {
            get {
                return this.purchaseMonthField;
            }
            set {
                this.purchaseMonthField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseYear {
            get {
                return this.purchaseYearField;
            }
            set {
                this.purchaseYearField = value;
            }
        }
        
        /// <remarks/>
        public int ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseWeight {
            get {
                return this.purchaseWeightField;
            }
            set {
                this.purchaseWeightField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FeedReport {
        
        private int schemeIdField;
        
        private int reportTypeField;
        
        private string feedMonthField;
        
        private string feedYearField;
        
        private string dateField;
        
        private string oB_AdultField;
        
        private string oB_GrowerField;
        
        private string oB_CreeperField;
        
        private string fP_AdultField;
        
        private string fP_GrowerField;
        
        private string fP_CreeperField;
        
        private string t_AdultField;
        
        private string t_GrowerField;
        
        private string t_CreeperField;
        
        private string fIB_AdultField;
        
        private string fIB_GrowerField;
        
        private string fIB_CreeperField;
        
        private string fIF_AdultField;
        
        private string fIF_GrowerField;
        
        private string cB_AdultField;
        
        private string cB_GrowerField;
        
        private string cB_CreeperField;
        
        /// <remarks/>
        public int SchemeId {
            get {
                return this.schemeIdField;
            }
            set {
                this.schemeIdField = value;
            }
        }
        
        /// <remarks/>
        public int ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FeedMonth {
            get {
                return this.feedMonthField;
            }
            set {
                this.feedMonthField = value;
            }
        }
        
        /// <remarks/>
        public string FeedYear {
            get {
                return this.feedYearField;
            }
            set {
                this.feedYearField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string OB_Adult {
            get {
                return this.oB_AdultField;
            }
            set {
                this.oB_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string OB_Grower {
            get {
                return this.oB_GrowerField;
            }
            set {
                this.oB_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string OB_Creeper {
            get {
                return this.oB_CreeperField;
            }
            set {
                this.oB_CreeperField = value;
            }
        }
        
        /// <remarks/>
        public string FP_Adult {
            get {
                return this.fP_AdultField;
            }
            set {
                this.fP_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string FP_Grower {
            get {
                return this.fP_GrowerField;
            }
            set {
                this.fP_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string FP_Creeper {
            get {
                return this.fP_CreeperField;
            }
            set {
                this.fP_CreeperField = value;
            }
        }
        
        /// <remarks/>
        public string T_Adult {
            get {
                return this.t_AdultField;
            }
            set {
                this.t_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string T_Grower {
            get {
                return this.t_GrowerField;
            }
            set {
                this.t_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string T_Creeper {
            get {
                return this.t_CreeperField;
            }
            set {
                this.t_CreeperField = value;
            }
        }
        
        /// <remarks/>
        public string FIB_Adult {
            get {
                return this.fIB_AdultField;
            }
            set {
                this.fIB_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string FIB_Grower {
            get {
                return this.fIB_GrowerField;
            }
            set {
                this.fIB_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string FIB_Creeper {
            get {
                return this.fIB_CreeperField;
            }
            set {
                this.fIB_CreeperField = value;
            }
        }
        
        /// <remarks/>
        public string FIF_Adult {
            get {
                return this.fIF_AdultField;
            }
            set {
                this.fIF_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string FIF_Grower {
            get {
                return this.fIF_GrowerField;
            }
            set {
                this.fIF_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string CB_Adult {
            get {
                return this.cB_AdultField;
            }
            set {
                this.cB_AdultField = value;
            }
        }
        
        /// <remarks/>
        public string CB_Grower {
            get {
                return this.cB_GrowerField;
            }
            set {
                this.cB_GrowerField = value;
            }
        }
        
        /// <remarks/>
        public string CB_Creeper {
            get {
                return this.cB_CreeperField;
            }
            set {
                this.cB_CreeperField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StockReportRetrieveCompletedEventHandler(object sender, StockReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StockReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StockReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FeedReportRetrieveCompletedEventHandler(object sender, FeedReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FeedReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FeedReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FeedReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FeedReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PurchaseReportRetrieveCompletedEventHandler(object sender, PurchaseReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PurchaseReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PurchaseReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PurchaseReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SellingReportRetrieveCompletedEventHandler(object sender, SellingReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellingReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellingReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SellingReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SellingReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeathReportRetrieveCompletedEventHandler(object sender, DeathReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeathReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeathReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeathReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeathReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DailyStockReportRetrieveCompletedEventHandler(object sender, DailyStockReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DailyStockReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DailyStockReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyStockReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyStockReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EconomicIndicesReportRetrieveCompletedEventHandler(object sender, EconomicIndicesReportRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EconomicIndicesReportRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EconomicIndicesReportRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EconomicIndicesReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EconomicIndicesReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PigGenerationRetrieveCompletedEventHandler(object sender, PigGenerationRetrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PigGenerationRetrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PigGenerationRetrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591